language: php

php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - 8.0.0-dev

before_script:
    - composer self-update
    - composer install --dev

script:
    - mkdir -p build/logs
    - make sniff test

after_script:
    - CODECLIMATE_REPO_TOKEN=15414484551ad327593cb7feb55d0e08bdd3409054111068b40215a8504232da ./vendor/bin/test-reporter
